#!/bin/bash
echo "🧙‍♂️ Nerd Font Installation Test 🧙‍♂️"
echo "=================================="
echo ""
echo "📋 Basic Unicode Symbols:"
echo "✅ ❌ 🔥 🚀 💻 🌟 ⚡ 🎯"
echo ""
echo "🔧 Powerline Symbols:"
echo "       "
echo ""
echo "💻 Development Icons:"
echo "     "
echo ""
echo "📁 File System Icons:"
echo "     "
echo ""
echo "🔀 Version Control:"
echo " ✓ ✗ ±"
echo ""
echo "🎨 Status Indicators:"
echo "● ○ ◆ ◇ ▶ ◀"
echo ""
echo "Test completed! If you see boxes or question marks,"
echo "your Nerd Font installation needs attention."
EOF
